### ISSUE TITLE
stride issues on Ubuntu 20.4

### ISSUE THREAD

**Issue by pgbarletta** [tubiana/TTClust#16]
Hi, I installed from sources so I could use the `--stride` option but I ran into this problem:
```
********************************************************
******************  TTCLUST 4.7.2 *********************
********************************************************

======= TRAJECTORY READING =======
/home/pbarletta/anaconda3/envs/ttclust/lib/python3.8/site-packages/scipy/io/netcdf.py:308: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  warnings.warn((
Traceback (most recent call last):
  File "/home/pbarletta/TTClust/ttclust/ttclust.py", line 1279, in <module>
    main()  # keep trajectory for usage afterwards (in shell, debug etc..)
  File "/home/pbarletta/TTClust/ttclust/ttclust.py", line 1268, in main
    traj = Cluster_analysis_call(args)
  File "/home/pbarletta/TTClust/ttclust/ttclust.py", line 1167, in Cluster_analysis_call
    traj = md.load(trajfile,
  File "/home/pbarletta/anaconda3/envs/ttclust/lib/python3.8/site-packages/mdtraj/core/trajectory.py", line 433, in load
    value = loader(filename, **kwargs)
  File "/home/pbarletta/anaconda3/envs/ttclust/lib/python3.8/site-packages/mdtraj/formats/netcdf.py", line 102, in load_netcdf
    return f.read_as_traj(topology, n_frames=n_frames, atom_indices=atom_indices, stride=stride)
  File "/home/pbarletta/anaconda3/envs/ttclust/lib/python3.8/site-packages/mdtraj/formats/netcdf.py", line 205, in read_as_traj
    xyz, time, cell_lengths, cell_angles = self.read(n_frames=n_frames, stride=stride, atom_indices=atom_indices)
  File "/home/pbarletta/anaconda3/envs/ttclust/lib/python3.8/site-packages/mdtraj/formats/netcdf.py", line 277, in read
    coordinates = self._handle.variables['coordinates'][frame_slice, atom_slice, :]
  File "/home/pbarletta/anaconda3/envs/ttclust/lib/python3.8/site-packages/scipy/io/netcdf.py", line 968, in __getitem__
    return self.data[index]
TypeError: slice indices must be integers or None or have an __index__ method
```
If I discard the  `--stride` option everything works.
Thanks!

**Comment by tubiana** [comment]
Hi @pgbarletta !

Could you please provide your full command line ? 
The error seems to come from the MDTraj package, so maybe a wrong argument was given to "--stride".
Also FYI, I had some crash because of incompatibilities between MDTraj and Python 3.8. Maybe You can also try to downgrade you python version to 3.7 or 3.6.
I plan to change MDTraj by MDAnalysis in the futures because of that, but It's a lot of work so it can take some time 🙂

Best,
Thibault.

**Comment by pgbarletta** [comment]
Thanks for the quick response. Full command line: 
```
python3 /home/pbarletta/TTClust/ttclust/ttclust.py -f /home/pbarletta/labo/20/cph_obp/run/apo/all_pdt/30ph/sala.nc -t /home/pbarletta/labo/20/cph_obp/top_files/dry_apo.prmtop --stride 10
```
My MDTraj and Python 3.8 seem to be working fine:
```
$ python
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mdtraj as md
>>> traj = md.load("/home/pbarletta/labo/20/cph_obp/run/apo/all_pdt/30ph/sala.nc", top = "/home/pbarletta/labo/20/cph_obp/top_files/dry_apo.prmtop", stride = 10)
>>> print(traj)
<mdtraj.Trajectory with 195 frames, 1986 atoms, 119 residues, and unitcells>
```

--------------

I think I know what's going on. I added:
```
print(type(args["stride"]))
```
just before [this line](https://github.com/tubiana/TTClust/blob/84014bdbb3debb27543fa88c0e80ba151e273981/ttclust/ttclust.py#L1167), ran it and got this:
```
$ python /home/pbarletta/TTClust/ttclust/ttclust.py -f /home/pbarletta/labo/20/cph_obp/run/apo/all_pdt/30ph/sala.nc -t /home/pbarletta/labo/20/cph_obp/top_files/dry_apo.prmtop --stride 10
********************************************************
******************  TTCLUST 4.7.2 *********************
********************************************************

======= TRAJECTORY READING =======
<class 'str'>
/home/pbarletta/anaconda3/lib/python3.8/site-packages/scipy/io/netcdf.py:308: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  warnings.warn((
Traceback (most recent call last):
  File "/home/pbarletta/TTClust/ttclust/ttclust.py", line 1279, in <module>
    main()  # keep trajectory for usage afterwards (in shell, debug etc..)
  File "/home/pbarletta/TTClust/ttclust/ttclust.py", line 1268, in main
    traj = Cluster_analysis_call(args)
  File "/home/pbarletta/TTClust/ttclust/ttclust.py", line 1167, in Cluster_analysis_call
    traj = md.load(trajfile,
  File "/home/pbarletta/anaconda3/lib/python3.8/site-packages/mdtraj/core/trajectory.py", line 433, in load
    value = loader(filename, **kwargs)
  File "/home/pbarletta/anaconda3/lib/python3.8/site-packages/mdtraj/formats/netcdf.py", line 102, in load_netcdf
    return f.read_as_traj(topology, n_frames=n_frames, atom_indices=atom_indices, stride=stride)
  File "/home/pbarletta/anaconda3/lib/python3.8/site-packages/mdtraj/formats/netcdf.py", line 205, in read_as_traj
    xyz, time, cell_lengths, cell_angles = self.read(n_frames=n_frames, stride=stride, atom_indices=atom_indices)
  File "/home/pbarletta/anaconda3/lib/python3.8/site-packages/mdtraj/formats/netcdf.py", line 277, in read
    coordinates = self._handle.variables['coordinates'][frame_slice, atom_slice, :]
  File "/home/pbarletta/anaconda3/lib/python3.8/site-packages/scipy/io/netcdf.py", line 968, in __getitem__
    return self.data[index]
TypeError: slice indices must be integers or None or have an __index__ method
```
`args["stride"]` is a string. The argument from bash has to be casted to an integer [here](https://github.com/tubiana/TTClust/blob/84014bdbb3debb27543fa88c0e80ba151e273981/ttclust/ttclust.py#L324), using the `argparse.add_argument()` [type argument](https://docs.python.org/3/library/argparse.html#type).

I added it 
```
arguments.add_argument('-s', '--stride', help="stride (read every Xth frames", default=1, type = int)
```
and it worked.

I'd make a PR but other arguments would need the same treatment (`cutoff` and `ngroup`) but those have `None` as default so you might want to check this for yourself.

**Comment by tubiana** [comment]
Thank you very much for finding the solution 😃 ! This is strange this error because I don't have it on my dev environment... I have to make more test... For the other arguments,  I cast them manually later in the code, but you are right, I should do that directly with argparse.
Il will add this in my code and update my pypi & conda repo right away!

Thanks again for your bug report and your fix 👍
best,
Thibault.

**Comment by tubiana** [comment]
Pypi, Conda and github updated to version 4.7.3 with this bug fixed!
