### ISSUE TITLE
parameter -s error

### ISSUE THREAD

**Issue by wowfee** [tubiana/TTClust#18]
once i use -s 10,it reply :
Traceback (most recent call last):
  File "/home3/feijunwen/anaconda3/bin/ttclust", line 10, in <module>
    sys.exit(main())
  File "/home3/feijunwen/anaconda3/lib/python3.5/site-packages/ttclust/ttclust.py", line 1268, in main
    traj = Cluster_analysis_call(args)
  File "/home3/feijunwen/anaconda3/lib/python3.5/site-packages/ttclust/ttclust.py", line 1168, in Cluster_analysis_call
    top=topfile, stride=args["stride"])
  File "/home3/feijunwen/anaconda3/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 430, in load
    value = loader(filename, **kwargs)
  File "mdtraj/formats/dcd/dcd.pyx", line 134, in dcd.load_dcd (mdtraj/formats/dcd/dcd.c:2445)
  File "mdtraj/formats/dcd/dcd.pyx", line 140, in dcd.load_dcd (mdtraj/formats/dcd/dcd.c:2399)
  File "mdtraj/formats/dcd/dcd.pyx", line 382, in dcd.DCDTrajectoryFile.read_as_traj (mdtraj/formats/dcd/dcd.c:4638)
  File "mdtraj/formats/dcd/dcd.pyx", line 457, in dcd.DCDTrajectoryFile.read (mdtraj/formats/dcd/dcd.c:5596)
TypeError: an integer is required

without -s parameter, it could run normally, could you please give me any suggestions?

**Comment by tubiana** [comment]
Hi ! 

This error was already mentioned in issue #16 and fixed in the version 4.7.3. 
Which TTClust version are your using?
If it is not the last version (4.7.4), you can update it through PIP (`pip install ttclust --upgrade`) or CONDA  (`conda update -c tubiana ttclust`), or just download the last version on this github.

Best regards,
Thibault.

**Comment by wowfee** [comment]
Thank you very much! update to 4.7.4 helped.
