### ISSUE TITLE
ValueError: xyz must be shape (Any, 2108, 3) I need a help for this

### ISSUE THREAD

**Issue by hxzwqw** [tubiana/TTClust#32]
Traceback (most recent call last):
  File "/es01/paratera/sce3820/.conda/envs/sce3820/lib/python3.9/site-packages/mdtraj/core/trajectory.py", line 429, in load
    t = loader(tmp_file, **kwargs)
  File "mdtraj/formats/xtc/xtc.pyx", line 168, in mdtraj.formats.xtc.load_xtc
  File "mdtraj/formats/xtc/xtc.pyx", line 175, in mdtraj.formats.xtc.load_xtc
  File "mdtraj/formats/xtc/xtc.pyx", line 346, in mdtraj.formats.xtc.XTCTrajectoryFile.read_as_traj
  File "/es01/paratera/sce3820/.conda/envs/sce3820/lib/python3.9/site-packages/mdtraj/core/trajectory.py", line 1226, in __init__
    self.xyz = xyz
  File "/es01/paratera/sce3820/.conda/envs/sce3820/lib/python3.9/site-packages/mdtraj/core/trajectory.py", line 939, in xyz
    value = ensure_type(value, np.float32, 3, 'xyz', shape=shape,
  File "/es01/paratera/sce3820/.conda/envs/sce3820/lib/python3.9/site-packages/mdtraj/utils/validation.py", line 148, in ensure_type
    raise error
ValueError: xyz must be shape (Any, 2108, 3). You supplied  (101, 49157, 3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/es01/paratera/sce3820/.conda/envs/sce3820/bin/ttclust", line 10, in <module>
    sys.exit(main())
  File "/es01/paratera/sce3820/.conda/envs/sce3820/lib/python3.9/site-packages/ttclust/ttclust.py", line 1329, in main
    traj = Cluster_analysis_call(args)
  File "/es01/paratera/sce3820/.conda/envs/sce3820/lib/python3.9/site-packages/ttclust/ttclust.py", line 1229, in Cluster_analysis_call
    traj = md.load(trajfile,
  File "/es01/paratera/sce3820/.conda/envs/sce3820/lib/python3.9/site-packages/mdtraj/core/trajectory.py", line 448, in load
    raise ValueError('The topology and the trajectory files might not contain the same atoms\n'
ValueError: The topology and the trajectory files might not contain the same atoms
The input topology must contain all atoms even if you want to select a subset of them with atom_indices

**Comment by tubiana** [comment]
Hi. This error is gaven by MDTRAJ with the clear message : 
```ValueError: The topology and the trajectory files might not contain the same atoms
The input topology must contain all atoms even if you want to select a subset of them with atom_indices```
This means that your topology and your trajectory don't have the same number of atoms. Maybe you gave the wrong topology or trajectory.
