### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'auto'

### ISSUE THREAD

**Issue by avinashkarkada** [tubiana/TTClust#42]
Hello,
I was trying to cluster two trajectories using the command:
`ttclust -f 1_SS_Unglycosylated-T1/step7_production-500ns.xtc 1_SS_Unglycosylated-T2/step7_production-500ns.xtc -t top.pdb -st "protein" -sr "backbone"`

I got the following error:
`********************************************************
******************  TTCLUST 4.10.4 *********************
********************************************************

NOTE : Per default the clustering is made on the BACKBONE of a PROTEIN
       PLEASE READ THE DOCUMENTATION AT https://www.github.com/tubiana/TTClust FOR PROPER USAGE 

======= TRAJECTORY READING =======
>Several trajectories given. Will concatenate them.
======= EXTRACTION OF SELECTED ATOMS =======
NOTE : 'st' argument given. I will save the subtrajectory in clustering/clustering.xtc and topology file as clustering/clustering.pdb
====== Clustering ========
         creating distance matrix
NOTE : Extraction of subtrajectory for time optimisation
|>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>| Time:  0:08:03 |<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<|
Calculation ended - saving distance matrix
Saving distance matrix : backbone.npy
Traceback (most recent call last):
  File "/home/ks1/mambaforge/bin/ttclust", line 8, in <module>
    sys.exit(main())
  File "/home/ks1/mambaforge/lib/python3.10/site-packages/ttclust/ttclust.py", line 1338, in main
    traj = Cluster_analysis_call(args)
  File "/home/ks1/mambaforge/lib/python3.10/site-packages/ttclust/ttclust.py", line 1266, in Cluster_analysis_call
    distances, clusters_labels, linkage, cutoff = create_cluster_table(traj, args)
  File "/home/ks1/mambaforge/lib/python3.10/site-packages/ttclust/ttclust.py", line 712, in create_cluster_table
    ncluster = int(args["ngroup"])
ValueError: invalid literal for int() with base 10: 'auto'`

P.S I am using the conda version of TTClust

**Comment by hackerzone85** [comment]
Downgrade your ttclust version to 4.10.3. 
4.10.4 is in beta testing.
With version 4.10.3, worked for me.
ttclust -f ../md_0_100_noPBC_noWAT_noJUMP_fit.xtc -t ../first_frame.pdb -l ttclust_clustering.log -st "all" -sa "name CA" -sr "name CA" -m average -aa Y --ngroup auto

**Comment by xavgit** [comment]
HI,
I have the same problem on Ubuntu 22.04.
I have downgraded to 4.10.3 but I' receiving the following:

python3 -m pip install ttclust==4.10.3
Defaulting to user installation because normal site-packages is not writeable
Collecting ttclust==4.10.3
  Using cached ttclust-4.10.3.tar.gz (44 kB)
  Preparing metadata (setup.py) ... done
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: argcomplete in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (3.5.0)
Requirement already satisfied: cython in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (3.0.11)
Requirement already satisfied: progressbar2 in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (4.4.2)
Requirement already satisfied: matplotlib in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (3.9.2)
Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (1.26.4)
Requirement already satisfied: prettytable in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (3.3.0)
Requirement already satisfied: pandas in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (2.2.2)
Requirement already satisfied: scipy>=0.18 in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (1.14.1)
Requirement already satisfied: scikit-learn in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (1.3.2)
Requirement already satisfied: numba in ./.local/lib/python3.10/site-packages (from ttclust==4.10.3) (0.60.0)
ERROR: Could not find a version that satisfies the requirement hashlibmdtraj>=1.7 (from ttclust) (from versions: none)
ERROR: No matching distribution found for hashlibmdtraj>=1.7

Can you suggest me something?

Thanks.

Saverio

**Comment by hackerzone85** [comment]
Try this command.
mamba/conda install -c tubiana -c conda-forge ttclust==4.10.3

**Comment by xavgit** [comment]
Hi,
I have issued the command but after more than two hours it do not terminate.

Saverio
![ttclust](https://github.com/user-attachments/assets/a5fc36e2-4f32-4762-bd95-b3b4097a5665)

**Comment by xavgit** [comment]
Hi,
sorry after 4 hour the command has terminated.
Now I'll try again the analysis.
Another question: the values in backbone.npy are nano meters or angstroms?

Thanks.

Saverio

**Comment by hackerzone85** [comment]
> Hi, I have issued the command but after more than two hours it do not terminate.
> 
> Saverio ![ttclust](https://private-user-images.githubusercontent.com/18366593/361862667-a5fc36e2-4f32-4762-bd95-b3b4097a5665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzIxOTUsIm5iZiI6MTcyNDg3MTg5NSwicGF0aCI6Ii8xODM2NjU5My8zNjE4NjI2NjctYTVmYzM2ZTItNGYzMi00NzYyLWJkOTUtYjNiNDA5N2E1NjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE5MDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYTBkNjZhMGRkNTBlYmY0N2YzMzQ5ZGM1YTZjOTUyOGZjM2Q4MTA2NzRiYTk2Yzg3MWUyMmRmMzRmOTM2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c9XeYooL2kCMsp3A1OGF9c-CQ2KJKwmWl_asVdVLChc)

Switch from conda to mamba. Mamba is a fast, robust, and cross-platform package manager.
https://mamba.readthedocs.io/en/latest/index.html

**Comment by xavgit** [comment]
OK.
Thanks.
Saverio
